# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class LocationEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Location static endpoint enum."""

    LOCATION = "Location"
    """Static endpoint"""


class NetworkEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Network static endpoint enum."""

    NETWORK = "Network"
    """Static endpoint"""


class NumberEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Number static endpoint enum."""

    NUMBER = "Number"
    """Static endpoint"""


class SimSwapEnum(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Number static endpoint enum."""

    SIM_SWAP = "SimSwap"
    """Static endpoint"""
